/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Devices;
import Database.SQLConnection;
import Controllers.DeviceController;
import Models.Device;
import Views.Home;
import Views.Perfil;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author gerar
 */
public class AgregarDispositivo extends javax.swing.JFrame {
    private String rut;
    private int idHome;
    
    public void setRutUser(String rut){
        this.rut = rut;
    }
    
    public void setIdHome(int id){
        this.idHome = id;
    }
    /**
     * Creates new form NewJFrame
     */
    public AgregarDispositivo() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnReturn1 = new javax.swing.JButton();
        AgregarTxt = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JLabel();
        ConsumoTxt = new javax.swing.JLabel();
        HorasTxt = new javax.swing.JLabel();
        PrioridadTxt = new javax.swing.JLabel();
        ClasificacionTxt = new javax.swing.JLabel();
        IngresoName = new javax.swing.JTextField();
        IngresoConsumo = new javax.swing.JTextField();
        IngresoHoras = new javax.swing.JTextField();
        IngresoPrioridadUso = new javax.swing.JTextField();
        IgresoClasificacion = new javax.swing.JTextField();
        Message = new javax.swing.JLabel();
        AGMessage = new javax.swing.JLabel();
        AceptarButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 255, 102));

        btnReturn1.setBackground(new java.awt.Color(0, 255, 102));
        btnReturn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha.png"))); // NOI18N
        btnReturn1.setBorder(null);
        btnReturn1.setContentAreaFilled(false);
        btnReturn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnReturn1)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnReturn1)
                .addContainerGap(444, Short.MAX_VALUE))
        );

        AgregarTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AgregarTxt.setForeground(new java.awt.Color(0, 0, 0));
        AgregarTxt.setText("Agregar Dispositivo");

        NombreTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NombreTxt.setForeground(new java.awt.Color(0, 0, 0));
        NombreTxt.setText("Nombre:");

        ConsumoTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConsumoTxt.setForeground(new java.awt.Color(0, 0, 0));
        ConsumoTxt.setText("Consumo de Energía:");

        HorasTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HorasTxt.setForeground(new java.awt.Color(0, 0, 0));
        HorasTxt.setText("Horas que esta Activo:");

        PrioridadTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PrioridadTxt.setForeground(new java.awt.Color(0, 0, 0));
        PrioridadTxt.setText("Prioridad de Uso:");

        ClasificacionTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClasificacionTxt.setForeground(new java.awt.Color(0, 0, 0));
        ClasificacionTxt.setText("Clasificación de Consumo:");

        IngresoName.setBackground(new java.awt.Color(255, 255, 255));
        IngresoName.setForeground(new java.awt.Color(0, 0, 0));
        IngresoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoNameActionPerformed(evt);
            }
        });

        IngresoConsumo.setBackground(new java.awt.Color(255, 255, 255));
        IngresoConsumo.setForeground(new java.awt.Color(0, 0, 0));

        IngresoHoras.setBackground(new java.awt.Color(255, 255, 255));
        IngresoHoras.setForeground(new java.awt.Color(0, 0, 0));
        IngresoHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoHorasActionPerformed(evt);
            }
        });

        IngresoPrioridadUso.setBackground(new java.awt.Color(255, 255, 255));
        IngresoPrioridadUso.setForeground(new java.awt.Color(0, 0, 0));
        IngresoPrioridadUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoPrioridadUsoActionPerformed(evt);
            }
        });

        IgresoClasificacion.setBackground(new java.awt.Color(255, 255, 255));
        IgresoClasificacion.setForeground(new java.awt.Color(0, 0, 0));
        IgresoClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgresoClasificacionActionPerformed(evt);
            }
        });

        Message.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Message.setForeground(new java.awt.Color(0, 0, 0));
        Message.setText("*Del 1-10");

        AGMessage.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        AGMessage.setForeground(new java.awt.Color(0, 0, 0));
        AGMessage.setText("*A-G");

        AceptarButton.setBackground(new java.awt.Color(0, 255, 102));
        AceptarButton.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        AceptarButton.setForeground(new java.awt.Color(0, 0, 0));
        AceptarButton.setText("Aceptar");
        AceptarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarButtonActionPerformed(evt);
            }
        });

        CancelarButton.setBackground(new java.awt.Color(0, 255, 102));
        CancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        CancelarButton.setForeground(new java.awt.Color(0, 0, 0));
        CancelarButton.setText("Cancelar");
        CancelarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PrioridadTxt)
                                .addGap(4, 4, 4)
                                .addComponent(IngresoPrioridadUso, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Message))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ClasificacionTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IgresoClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AGMessage))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NombreTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IngresoName, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(HorasTxt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(IngresoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(ConsumoTxt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(IngresoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(AceptarButton)
                        .addGap(75, 75, 75)
                        .addComponent(CancelarButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(AgregarTxt)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AgregarTxt)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreTxt)
                    .addComponent(IngresoName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsumoTxt)
                    .addComponent(IngresoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HorasTxt)
                    .addComponent(IngresoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrioridadTxt)
                    .addComponent(IngresoPrioridadUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Message))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClasificacionTxt)
                    .addComponent(IgresoClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AGMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarButton)
                    .addComponent(CancelarButton))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresoHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresoHorasActionPerformed

    private void IngresoPrioridadUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoPrioridadUsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresoPrioridadUsoActionPerformed

    private void IgresoClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgresoClasificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IgresoClasificacionActionPerformed

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
        // TODO add your handling code here:
        MenuDispositivos menu = new MenuDispositivos();
        menu.setVisible(true);
        menu.setRutUser(rut);
        menu.setIdHome(idHome);
        this.setVisible(false);
    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void btnReturn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturn1ActionPerformed
        MenuDispositivos menuPrincipal = new MenuDispositivos();
        menuPrincipal.setVisible(true);
        menuPrincipal.setRutUser(rut);
        menuPrincipal.setIdHome(idHome);
        this.setVisible(false);
    }//GEN-LAST:event_btnReturn1ActionPerformed

    private void IngresoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresoNameActionPerformed

    private void AceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarButtonActionPerformed
        DeviceController controlador = new DeviceController();
        SQLConnection conexion = new SQLConnection();
        int id = (controlador.obtenerUltimoIdDevice() + 1);
        String sql = "INSERT INTO Devices_Home (ID_Device, ID_HOME) values (" + id + ", " + this.idHome + ")";
        
        Device nuevo = new Device(id, IngresoName.getText(), Double.valueOf(IngresoConsumo.getText()), 
                Float.valueOf(IngresoHoras.getText()), Integer.valueOf(IngresoPrioridadUso.getText()), 
                (IgresoClasificacion.getText()).charAt(0));
        controlador.agregarDeviceABD(nuevo);
        conexion.conectar();
        conexion.ejecutarConsulta(sql);
        conexion.desconectar();
        JOptionPane.showMessageDialog(this, "Dispositivo agregado correctamente");
        MenuDispositivos menu = new MenuDispositivos();
        menu.setVisible(true);
        menu.setRutUser(rut);
        menu.setIdHome(idHome);
        this.setVisible(false);
    }//GEN-LAST:event_AceptarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarDispositivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarDispositivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarDispositivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarDispositivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarDispositivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AGMessage;
    private javax.swing.JButton AceptarButton;
    private javax.swing.JLabel AgregarTxt;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JLabel ClasificacionTxt;
    private javax.swing.JLabel ConsumoTxt;
    private javax.swing.JLabel HorasTxt;
    private javax.swing.JTextField IgresoClasificacion;
    private javax.swing.JTextField IngresoConsumo;
    private javax.swing.JTextField IngresoHoras;
    private javax.swing.JTextField IngresoName;
    private javax.swing.JTextField IngresoPrioridadUso;
    private javax.swing.JLabel Message;
    private javax.swing.JLabel NombreTxt;
    private javax.swing.JLabel PrioridadTxt;
    private javax.swing.JButton btnReturn1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
